### ISSUE TITLE
Builds aren't visible

### ISSUE THREAD

**Issue by JSGette** [buildbarn/bb-portal#1]
I've added the following flags to my command:
`--bes_backend=grpc://localhost:8082 --bes_results_url=http://localhost:8081/bazel-invocations`

but Builds tab is empty. I can see my invocations in the invocations tab but they don't contain any useful information:
![image](https://github.com/buildbarn/bb-portal/assets/9263589/c2b3a62f-6633-4d6d-9b2e-7a3f145fcc2b)

![image](https://github.com/buildbarn/bb-portal/assets/9263589/ca95dc90-5be0-4a78-bb2a-336e39dd6f7d)

Bazel version I am using:
```
Build label: 7.1.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Mar 11 17:55:31 2024 (1710179731)
Build timestamp: 1710179731
Build timestamp as int: 1710179731
```

**Comment by EdSchouten** [comment]
Hey! Did you set the `BUILD_URL` environment variable? You could let that point to the URL of your CI system that kicks off the build.

From the README:
> Buildbarn Portal groups Bazel invocations into builds based on the observed setting of the `BUILD_URL` environment variable.
If this environment variable is set during an invocation, the invocation will be attributed to a build as identified by the URL.
Buildbarn Portal displays analyzed build output either for individual Bazel invocations, or for builds comprising multiple Bazel invocations.
The grouping of Bazel invocations by build is a differentiating feature of the Buildbarn Portal.

**Comment by EdSchouten** [comment]
> But just to make it clear, right now bb-portal would only show debug information of the failed invocation, right? Build log of a successful one won't be present, correct?

I think that is correct. But contributions to generalize bb-portal to allow accessing information pertaining to successful builds are more than welcome!
